<?php

namespace app\Models;

use src\Model;

class Session extends Model{

	public function getUser()
	{
		return User::findOne($this->id_user);
	}

	public function jsonSerialize(): mixed
	{
		$attr = parent::jsonSerialize(); // TODO: Change the autogenerated stub
		$attr['user'] = $this->getUser();
		unset($attr['user']['password']);
		return $attr;
	}
}