<?php

namespace app\Models;

use src\Model;

/**
 * @property int id_user
 */
class Session extends Model{

	public function getUser(): ?User
	{
		if(empty($this->id_user)) {
			return null;
		}
		return User::findOne($this->id_user);
	}

	public function jsonSerialize(): mixed
	{
		$attr = parent::jsonSerialize(); // TODO: Change the autogenerated stub
		$attr['user'] = $this->getUser();
		unset($attr['user']['password']);
		return $attr;
	}
}